### ISSUE TITLE
【CSS】

### ISSUE THREAD

**Issue by Jerry1562** [Jerry1562/ownmemory.github.io#11]
**一、列表**
>1.`list-style-type`标志形状，属性的值可查[属性表](http://www.w3school.com.cn/cssref/pr_list-style-type.asp)
```CSS
li {list-style-type : square}
```
>2.`list-style-image`使用自定义图像做标志，该属性会把`list-style-type`的效果覆盖掉
```CSS
li {list-style-image : url(xxx.gif)}
```
>3.`list-style-position`标志在行内的位置，有三个值

 inside | outside | inherit
--------|----------|---------
放置在行内，属于文本部分 | 放置在行外，不属于文本部分 | 继承父元素的值
```CSS
li {list-style-position : inside}
```
>4.简写：
```CSS
li {list-style : url(example.gif) square inside}
```
**二、表格**
>1.
