### ISSUE TITLE
对使用float方法居中元素的思考

### ISSUE THREAD

**Issue by Jerry1562** [Jerry1562/ownmemory.github.io#14]
在学习水平居中的时候，有方法如下：
```CSS
.parent{
      float:left;
      position:relative;
      left:50%;
      border:1px solid blue;//加入框便于观察元素的边界
}
.child{
      background-color:green;//同理，便于观察
      position:relative;
      right:50%;
}
```
自然我是很奇怪的，`float`的作用到底是什么，之前我们不是只用两次`position`就可以把元素居中的吗
于是我查看了之前的代码
```CSS
.parent{
border:1px solid green;
height:200px;
width:300px;
position:relative;
left:50%;
}
.child{
position:relative;
right:50%;
}
```
我画了一个框，长宽为200px、300px，对于这个框来说，经过了上面的样式处理，它确实被居中了。
**同理，对于没有被设置大小的div元素来说，他的宽度等于页面宽度，经过处理后，这个框回到了出发点，某种意义上说，它也被成功居中了。**
但是，对于框中的内容来说，却没有被居中，比如说那些不足一行的文字，它又回到了出发点，还是原来的状态。
于是，自然而然地可以想到，**当框刚好包裹住文字的时候，框居中不就等于文字居中了吗？所以，我们要做的，就是让元素框的大小刚好等于内容的大小，这可以说是居中的核心思想。**
首先拿出的方案是`display:table`,利用`table`的特性包裹文本内容。
然后联系一下`float`的特性，`float`浮动具有破坏性，包裹行为，他会把原来的框破坏掉，对于本例来说，原本的div框被破坏，再把文本内容包裹起来，于是乎，框的大小就等于内容的大小，目的达成，思想与`display:table;`是一致的。
