### ISSUE TITLE
CSS小练习

### ISSUE THREAD

**Issue by Jerry1562** [Jerry1562/ownmemory.github.io#24]
1、要求
![360 20180531114140106](https://user-images.githubusercontent.com/36063897/40787294-d2afd9c6-651f-11e8-852d-2b2805f0f95d.jpg)
2、代码
**CSS部分**
```css
<style type="text/css">
     .st{
         width:200px;
         height:50px;
         
         background:blue no-repeat url('bg.jpg') center left;
         
         border:5px dashed green;
         
         text-align: left;
         line-height:50px;

         border-radius: 3px;       /* 圆角边框 */

         box-shadow: 1px 2px 3px;  /* 设计边框阴影 */

         position:fixed;           /*浮动居中的方法*/
         left:0;
         right:0;
         top:0;
         bottom:0;
         margin:auto auto;
     }
     .clear{
         clear:both;                /* 清除浮动 */
     }
    </style>
```
**body部分**
```html
<body>
<input type="text" class="st"/>
<div class="clear"></div>  
</body>
```
3、结果
![360 20180531222058797](https://user-images.githubusercontent.com/36063897/40787730-ebf3bf1e-6520-11e8-81b1-7a41884615ea.jpg)
对于视窗一直保持居中
