### ISSUE TITLE
【CSS学习】小坑

### ISSUE THREAD

**Issue by Jerry1562** [Jerry1562/ownmemory.github.io#7]
**使用Chrome测试**
**Chrome不支持text-decoration属性的blink值**
在解析CSS规则时，当某一项声明属性或者它的值不被支持，此声明将会被忽略，后面的属性一样会被读取。
如：
```CSS
a{
text-decoration:blink;
color:red;       //显示red
}
```
